-- Create notifications table
create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade not null,
    title text not null,
    message text not null,
    type text not null, -- 'review', 'system', 'claim_update', etc.
    link text, -- URL to redirect to
    is_read boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table public.notifications enable row level security;

create policy "Users can view their own notifications"
    on public.notifications for select
    using (auth.uid() = user_id);

create policy "Users can update their own notifications (mark as read)"
    on public.notifications for update
    using (auth.uid() = user_id);

-- Only system/admins can insert (usually done via server actions with service role or triggers)
-- For now, we allow authenticated users to insert if they are triggering an action (like a review)
-- meaningful security would likely require a trigger function or service role,
-- but for this app architecture, we'll allow insert for now or rely on server actions.
create policy "Authenticated users can insert notifications"
    on public.notifications for insert
    with check (auth.role() = 'authenticated');
