-- Salary retention: subscriptions for role/city, sector/city and company salary updates.

create table if not exists public.salary_alert_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  scope text not null check (scope in ('company', 'role_city', 'sector_city')),
  business_id text references public.businesses(id) on delete cascade,
  role_slug text,
  sector_slug text,
  city_slug text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ensure each scope has required fields.
alter table public.salary_alert_subscriptions
  drop constraint if exists salary_alert_company_scope_ck;

alter table public.salary_alert_subscriptions
  add constraint salary_alert_company_scope_ck
  check (
    (scope <> 'company')
    or (business_id is not null and role_slug is null and sector_slug is null and city_slug is null)
  );

alter table public.salary_alert_subscriptions
  drop constraint if exists salary_alert_role_city_scope_ck;

alter table public.salary_alert_subscriptions
  add constraint salary_alert_role_city_scope_ck
  check (
    (scope <> 'role_city')
    or (role_slug is not null and city_slug is not null and business_id is null and sector_slug is null)
  );

alter table public.salary_alert_subscriptions
  drop constraint if exists salary_alert_sector_city_scope_ck;

alter table public.salary_alert_subscriptions
  add constraint salary_alert_sector_city_scope_ck
  check (
    (scope <> 'sector_city')
    or (sector_slug is not null and city_slug is not null and business_id is null and role_slug is null)
  );

create unique index if not exists salary_alert_company_unique_idx
  on public.salary_alert_subscriptions (user_id, business_id)
  where scope = 'company';

create unique index if not exists salary_alert_role_city_unique_idx
  on public.salary_alert_subscriptions (user_id, role_slug, city_slug)
  where scope = 'role_city';

create unique index if not exists salary_alert_sector_city_unique_idx
  on public.salary_alert_subscriptions (user_id, sector_slug, city_slug)
  where scope = 'sector_city';

create index if not exists salary_alert_scope_city_idx
  on public.salary_alert_subscriptions (scope, city_slug);

drop trigger if exists trg_salary_alert_subscriptions_updated_at on public.salary_alert_subscriptions;
create trigger trg_salary_alert_subscriptions_updated_at
before update on public.salary_alert_subscriptions
for each row execute function public.update_updated_at_column();

alter table public.salary_alert_subscriptions enable row level security;

drop policy if exists "Users can view own salary alert subscriptions" on public.salary_alert_subscriptions;
create policy "Users can view own salary alert subscriptions"
  on public.salary_alert_subscriptions for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own salary alert subscriptions" on public.salary_alert_subscriptions;
create policy "Users can insert own salary alert subscriptions"
  on public.salary_alert_subscriptions for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own salary alert subscriptions" on public.salary_alert_subscriptions;
create policy "Users can delete own salary alert subscriptions"
  on public.salary_alert_subscriptions for delete
  using (auth.uid() = user_id);
