-- Referral trust, safety, moderation and reputation hardening.

alter table public.job_referral_offers
  add column if not exists identity_level text not null default 'anonymous'
    check (identity_level in ('anonymous', 'public', 'verified_employee')),
  add column if not exists verification_status text not null default 'unverified'
    check (verification_status in ('unverified', 'pending', 'verified', 'rejected')),
  add column if not exists trust_score smallint not null default 40
    check (trust_score between 0 and 100),
  add column if not exists response_rate numeric(5,2) not null default 0
    check (response_rate between 0 and 100),
  add column if not exists response_hours_avg integer,
  add column if not exists successful_referrals integer not null default 0
    check (successful_referrals >= 0),
  add column if not exists closed_by_owner_at timestamptz,
  add column if not exists moderation_reason text,
  add column if not exists moderated_at timestamptz;

alter table public.job_referral_requests
  add column if not exists response_due_at timestamptz;

create index if not exists idx_job_referral_offers_city_status_created
  on public.job_referral_offers(city, status, created_at desc);

create index if not exists idx_job_referral_offers_status_expires
  on public.job_referral_offers(status, expires_at);

create table if not exists public.job_referral_offer_reports (
  id bigint generated by default as identity primary key,
  offer_id uuid not null references public.job_referral_offers(id) on delete cascade,
  reporter_user_id uuid not null references public.profiles(id) on delete cascade,
  reason text not null check (reason in ('scam', 'impersonation', 'spam', 'off_platform', 'payment_request', 'other')),
  details text,
  status text not null default 'open' check (status in ('open', 'investigating', 'resolved', 'dismissed')),
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  moderation_note text,
  unique (offer_id, reporter_user_id)
);

create index if not exists idx_referral_offer_reports_offer_status
  on public.job_referral_offer_reports(offer_id, status, created_at desc);

create index if not exists idx_referral_offer_reports_reporter
  on public.job_referral_offer_reports(reporter_user_id, created_at desc);

drop trigger if exists trg_job_referral_offer_reports_updated_at on public.job_referral_offer_reports;
create trigger trg_job_referral_offer_reports_updated_at
before update on public.job_referral_offer_reports
for each row execute function public.update_updated_at_column();

create table if not exists public.job_referral_user_blocks (
  id bigint generated by default as identity primary key,
  blocker_user_id uuid not null references public.profiles(id) on delete cascade,
  blocked_user_id uuid not null references public.profiles(id) on delete cascade,
  reason text,
  created_at timestamptz not null default timezone('utc'::text, now()),
  unique (blocker_user_id, blocked_user_id),
  check (blocker_user_id <> blocked_user_id)
);

create index if not exists idx_referral_user_blocks_blocker
  on public.job_referral_user_blocks(blocker_user_id, created_at desc);

create index if not exists idx_referral_user_blocks_blocked
  on public.job_referral_user_blocks(blocked_user_id, created_at desc);

alter table public.job_referral_offer_reports enable row level security;
alter table public.job_referral_user_blocks enable row level security;

drop policy if exists "Users can create referral offer reports" on public.job_referral_offer_reports;
create policy "Users can create referral offer reports"
on public.job_referral_offer_reports for insert
to authenticated
with check (
  auth.uid() = reporter_user_id
  and exists (
    select 1
    from public.job_referral_offers o
    where o.id = offer_id
  )
);

drop policy if exists "Users can read own referral reports" on public.job_referral_offer_reports;
create policy "Users can read own referral reports"
on public.job_referral_offer_reports for select
to authenticated
using (auth.uid() = reporter_user_id);

drop policy if exists "Users can block referral users" on public.job_referral_user_blocks;
create policy "Users can block referral users"
on public.job_referral_user_blocks for insert
to authenticated
with check (auth.uid() = blocker_user_id);

drop policy if exists "Users can read own referral blocks" on public.job_referral_user_blocks;
create policy "Users can read own referral blocks"
on public.job_referral_user_blocks for select
to authenticated
using (auth.uid() = blocker_user_id);

drop policy if exists "Users can remove own referral blocks" on public.job_referral_user_blocks;
create policy "Users can remove own referral blocks"
on public.job_referral_user_blocks for delete
to authenticated
using (auth.uid() = blocker_user_id);
